### ISSUE TITLE
mkiraf not working, wrong path

### ISSUE THREAD

**Issue by juliotux** [astroconda/astroconda-iraf#7]
Using the astroconda version of IRAF, the command `mkiraf` do not work, due to a wrong path of the default `login.cl` file. The full error reported is:

```
[julio@coaa100 ~]$ mkiraf
Initialize uparm? (y|n): y
-- initializing uparm
Terminal types: xgterm,xterm,gterm,vt640,vt100,etc.
Enter terminal type [default xterm-256color]: xgterm
/home/julio/.anaconda3/bin/mkiraf: line 126: /unix/hlib/login.cl: No such file or directory
A new LOGIN.CL file has been created in the current directory.
You may wish to review and edit this file to change the defaults.
You may also add additional customizations to loginuser.cl
```
And no `login.cl` is created.

**Comment by juliotux** [comment]
In reality, this is not exactly a bug. To use `mkiraf` it is needed to activate the installed environment, so it work fine.

**Comment by jehturner** [comment]
That's good. Can I ask what Anaconda version you are using here? I haven't seen this before and it does seem like a potential source of confusion.

**Comment by juliotux** [comment]
I use Anaconda 5.2, with Python 3.7.

**Comment by jehturner** [comment]
It's really not clear to me how mkiraf ends up in `~/.anaconda3/bin`. I know files can get installed in that parent directory eg. if you create a new environment on top of a read-only installation, but then they go into an envs/ subdirectory; bin/ would therefore appear to correspond to something overlaid on the base environment, but attempting to install into the latter just produces a `Read-only file system` error for me. So I'm not sure how to reproduce that, but I don't think you should normally end up with `mkiraf` installed there.

Or is `~/.anaconda3` just where the GUI installer puts the main install now? I think it's actually `~/.conda` that I was remembering, where packages get installed to when the main installation is read-only. I that case, the reason for the weird behaviour is (at least partly) that you seem to have installed `iraf` into the base environment by mistake, instead of your own env.

**Comment by juliotux** [comment]
I installed the iraf packages in the base environment. Activating the base before use mkiraf and iraf works just fine. This is why I closed the issue, my fault.

**Comment by jehturner** [comment]
OK, thanks for the clarification.
