### ISSUE TITLE
pyraf

### ISSUE THREAD

**Issue by achillefiore** [astroconda/astroconda-iraf#9]
Hi all, do you know how/whether is it still possible to download the patch to upgrade pyraf to v2.15.1a ( see http://www.stsci.edu/institute/software_hardware/pyraf/pyraf_faq )? Currently if I type:

>pyraf -V
>2.1.15

I read there should be some ftp archive ( http://iraf.noao.edu/v2151a-announce.txt ) to do it, but I don't understand how to do it. 
Thank you! Cheers

**Comment by jehturner** [comment]
Hello. Sorry you didn't receive a reply to this when you asked (I'm just clearing out some old issues before this repo gets archived). I'm not aware of a link to the old NOAO IRAF information on the NOIR Lab pages, but should you need it, there is a newer (Python-3-compatible) PyRAF v2.2.1 at https://github.com/iraf-community/pyraf, with is a conda package build in the channel http://astroconda.gemini.edu/public (since STScI has decided to stop supporting its Astroconda channel).
